### ISSUE TITLE
Questions about the equivalent gaussian filter radius and the standard deviation of DDK filtered SHCs for GRACE-filter

### ISSUE THREAD

**Issue by lcx366** [strawpants/GRACE-filter#1]
Dear Dr. Rietbroek,

I have two questions about the GRACE-filter package. 1. What are the equivalent Gaussian filter radius for DDK1-DDK8? Although the Gaussian filter radius of DDK1-DDK3 has been mentioned in your article, how about DDK4~DDK8? Can you simply summarize how to estimate the corresponding Gaussian filter radius? 2. How to calculate the standard deviation of the DDK filtered Stokes coefficient by the law of error propagation? If they are important, can GRACE-filter calculate them? Or is there a viable program or code?

Best regards,

C. Li

**Comment by strawpants** [comment]
Hi Li,

the question on what is the "equivalent" Gaussian half-width radius of the DDK filters has always been a difficult one. 

The short, and unsatisfying, answer is that there is none, because the shape of the DDK kernel changes depending on where you're filtering, and it is directionally dependent. Nevertheless, to get an impression on the spatial scales of the filter, I usually find it informative to filter a spherical harmonic expansion of a point load on a geographical point of interest and filter that with the DDK filters. This essentially provides you with the shape of the filter kernel at the position of interest. You can have a look [here](https://github.com/strawpants/GRACE-filter/blob/master/doc/Visualized_DDKkernels.pdf) on how these kernels look like and see at what extent the weight has decreased by half.

Hope this helps a bit,

Roelof 

PS:
Note that the spherical harmonic expansion coefficient of a unit point load at lat,lon can just be expressed as:
Cnm=Ynm(lat,lon)
Where Ynm is the 4pi normalized real surface spherical harmonic basis function.

**Comment by lcx366** [comment]
Thank you for your wonderful answer. Can you extend the function 'filterSH(W,cnm,snm)' to also allow error propagation ?

**Comment by strawpants** [comment]
That's a good idea, but I'll probably only do diagonal error propagation at this stage.

**Comment by strawpants** [comment]
Diagonal error propagation is now enabled since commit a8eaa93c2fec7a1043d1188cdb627721fa2407f8
